### ISSUE TITLE
open-source code when no external feedback 

### ISSUE THREAD

**Issue by free2ride19** [actions/first-interaction#94]
Thank you 🙇‍♀ for wanting to create an issue in this repository. Before you do, please ensure you are filing the issue in the right place. Issues should only be opened on if the issue **relates to code in this repository**.

* If you have found a security issue [please submit it here](https://hackerone.com/github)
* If you have questions about writing workflows or action files, then please [visit the GitHub Community Forum's Actions Board](https://github.community/c/code-to-cloud/github-actions)
* If you are having an issue or question about GitHub Actions then please [contact customer support](https://help.github.com/en/articles/about-github-actions#contacting-support)

If your issue is relevant to this repository, please delete this text and continue to create this issue. Thank you in advance.

**Comment by free2ride19** [comment]
need for speed in work space velocity.

**Comment by The11sun** [comment]
I don't know...that I know..there are people who only hope for benefits
from me..until I'm confused...then let me trust you..so I leave you to
think about it as homework...but trust me.  .I don't do it
regularly..but....it's a way of saying..I can't trust anyone....and I
won't...because I just have to eat and use.

ในวันที่ จ. 18 ก.ค. 2022 12:35 น. AIFUWA OMOREGBEE ***@***.***>
เขียนว่า:

**Comment by poamaechi** [comment]
Ok so what is the issue with trusts here
